title = "zetc0de — IT Security Enthusiast"
baseurl = "https://zetc0de.github.io/"
languageCode = "id-id"
defaultContentLanguage = "id"


copyright = "Copyright © 2020, zetc0de and the Hugo Authors; all rights reserved."
theme = "npq-hugo"
pygmentsUseClasses=true

[params]
  author = "Mas Zet"
  description = "IT Security Enthusiast"
  keywords = "Exploit | IT Security | Bug Bounty | HTB | Hacking | Pentest | Red Team"
  useAvatar = true
  microBlogSection = "posts"
  displayMicroBlog = true
  displayRecent = true
  recentMax = 4
  mail = "zetc0de.id@gmail.com"
  phone = "https://t.me/zetc0de"
  formspreeID = "xrgyeopo"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<i class=\"fas fa-home fa-sm\"></i>"
    url = "/"
    weight = -9 
  [[menu.main]]
    name = "Articles"
    pre = "<i class=\"fas fa-keyboard fa-ms\"></i>"
    url = "/post/"
    weight = -8
  [[menu.main]]
    name = "Tags"
    pre = "<i class=\"fas fa-tags fa-ms\"></i>"
    url = "/tags"
    weight = -7 
  [[menu.main]]
    name = "Labs"
    pre = "<i class=\"fas fa-server fa-ms\"></i>"
    url = "/labs"
    weight = -6

  [[menu.main]]
    name = "Github"
    pre = "<i class=\"fab fa-github fa-ms\"></i>"
    url = "https://github.com/zetc0de"
    weight = -5
  [[menu.main]]
    name = "RSS"
    pre = "<i class=\"fas fa-rss fa-ms\"></i>"
    url = "/index.xml"
    weight = -4 
#  [[menu.main]]
#    name = "contact"
#    pre = "<i class=\"far fa-envelope\"></i>"
#    url = "/contact"
#    weight = -1 